### ISSUE TITLE
[Feat] 밴드 타임라인에 항목들을 만들어둔 목데이터에서 불러와서 출력하도록 구현합니다.

### ISSUE THREAD

**Issue by taehyeonk** [DeveloperAcademy-POSTECH/MacC-GetARock#108]
## 💡 Issue

밴드 타임라인 화면 연결 이후, 임시로 만들어둔 데이터를 삭제하고 공동으로 사용하기로한 목데이터에서 정보를 불러와서 타임라인 목록을 출력하도록 구현합니다.

## 📝  todo

- [x] 임시 데이터 삭제
- [x] 목데이터 연결

**Comment by skycat0212** [comment]
https://github.com/DeveloperAcademy-POSTECH/MacC-GetARock/pull/110#discussion_r1037290156 도 같이 확인 부탁드려요!
