### ISSUE TITLE
[Bug] 모여락 장소 선택시 "주변 검색" 선택시 모여락 추가 뷰컨트롤러가 닫히는 문제

### ISSUE THREAD

**Issue by EuniceNam** [DeveloperAcademy-POSTECH/MacC-GetARock#124]
# 🐞 버그 설명
| 문제 발생 일시 |  발생 위치  | 발생 조건 | 관련 이슈 |
|:---:|:---:|:---:|:---:|
| 2022.12.5. 리허설 | 모여락 추가 > 장소 검색 | "광흥창" 등 검색시 나오는 "주변 검색" 셀 탭 | #38 |

## 증상 

장소 검색 결과가 없을 때 모여락 추가 모달이 아예 닫히는 문제

## 스크린샷

![Simulator Screen Recording - 6s-15 0 - 2023-01-26 at 18 22 51](https://user-images.githubusercontent.com/18394923/214800739-00900c86-5268-4605-a2dc-748df26fe041.gif)

**Comment by compuTasha** [comment]
앗 나중에 스크린샷도 추가해주시면 좋을 것 같습니다
